export const UrlConst = {
    TERRAIN_BLOCKED:"assets/terrain/hex_grass.png",
    TERRAIN_RESOURCE:"assets/terrain/hex_grass.png",
    TERRAIN_CITY:"assets/terrain/hex_plain.png",
    TERRAIN_WATER:"assets/terrain/hex_water.png",
    TERRAIN_BRIDGE:"assets/terrain/hex_bridge.png",
    TERRAIN_CARD_HOLDER:"assets/terrain/hex_stash_close.png",
    TERRAIN_CARD_HOLDER_OPEN:"assets/terrain/hex_stash_open.png",
    TERRAIN_ROAD:"assets/terrain/hex_road.png",
    /* TERRAIN_BLOCKED:"assets/terrain/Plain Block.png",
    TERRAIN_RESOURCE:"assets/terrain/Grass Block.png",
    TERRAIN_CITY:"assets/terrain/Dirt Block.png",
    TERRAIN_WATER:"assets/terrain/Water Block.png",
    TERRAIN_BRIDGE:"assets/terrain/Wood Block.png",
    TERRAIN_CARD_HOLDER:"assets/resources/Chest Closed.png",
    TERRAIN_CARD_HOLDER_OPEN:"assets/resources/Chest Open.png", */
    //TERRAIN_ROAD:"assets/terrain/Stone Block.png",
    TERRAIN_EXPLOSION:"assets/resources/explosion.png",

    ROAD:"assets/terrain/hex_road.png",

    CHURCH1:"assets/buildings/church1.png",
    CHURCH2:"assets/buildings/church2.png",
    CHURCH3:"assets/buildings/church3.png",
    CHURCH4:"assets/buildings/church3.png",
    CHURCH5:"assets/buildings/church3.png",
    CHURCH6:"assets/buildings/church3.png",

    HOUSE1:"assets/buildings/house1b.png",
    HOUSE2:"assets/buildings/house.png",
    HOUSE3:"assets/buildings/house2.png",
    HOUSE4:"assets/buildings/house3.png",
    HOUSE5:"assets/buildings/house3.png",
    HOUSE6:"assets/buildings/house3.png",

    STORAGE1:"assets/buildings/storage1.png",
    STORAGE2:"assets/buildings/storage.png",
    STORAGE3:"assets/buildings/storage.png",
    STORAGE4:"assets/buildings/storage.png",
    STORAGE5:"assets/buildings/storage.png",
    STORAGE6:"assets/buildings/storage.png",

    SAWMILL1:"assets/buildings/sawmil.png",
    SAWMILL2:"assets/buildings/sawmil.png",
    SAWMILL3:"assets/buildings/sawmil.png",
    SAWMILL4:"assets/buildings/sawmil.png",
    SAWMILL5:"assets/buildings/sawmil.png",
    SAWMILL6:"assets/buildings/sawmil.png",

    LABORATORY:"assets/buildings/lab.png",
    PALACE:"assets/buildings/laboratory.png",
    



    BRICK1:"assets/resources/hex_brick1.png",
    BRICK2:"assets/resources/hex_brick2.png",
    BRICK3:"assets/resources/hex_brick3.png",
    BRICK3_4:"assets/resources/hex_brick4_2.png",
    BRICK3_5:"assets/resources/hex_brick4_3.png",
    BRICK3_6:"assets/resources/hex_brick4_4.png",
    BRICK4:"assets/resources/hex_brick5.png",
    BRICK5:"assets/resources/hex_brick6.png",
    BRICK6:"assets/resources/hex_brick7.png",

    LUMBER1:"assets/resources/hex_lumber1.png",
    LUMBER2:"assets/resources/hex_lumber2.png",
    LUMBER3:"assets/resources/hex_lumber3.png",
    LUMBER4:"assets/resources/hex_lumber4.png",
    LUMBER5:"assets/resources/hex_lumber5.png",
    LUMBER6:"assets/resources/hex_lumber6.png",

    COIN_IMG:"assets/resources/hex_coin_icon.png",
    BRICK_IMG:"assets/resources/hex_brick_icon.png",
    LUMBER_IMG:"assets/resources/hex_lumber_icon.png",

    COIN:"assets/resources/hex_coin_gold.png",
    COIN_SILVER:"assets/resources/hex_coin_silver.png",
    WILD:"assets/resources/hex_wild.png",

    //PERSON1:"assets/people/Character Boy.png",
    PERSON1:"assets/people/person1.png",
   // PERSON2:"assets/people/Character Cat Girl.png",
    PERSON2:"assets/people/person2.png",
    PERSON3:"assets/people/Character Horn Girl.png",
    PERSON4:"assets/people/Character Pink Girl.png",

    BONES:"assets/resources/hex_bones.png",
    OIL1:"assets/resources/hex_oil.png",
    OIL2:"assets/resources/hex_oil1.png",
    OIL3:"assets/resources/hex_oil2.png",
    ZOOMBIE:"assets/people/zombiePig.png",
    ANIMAL:"assets/people/animal1.png",
    ANIMAL2:"assets/people/animal2.png",
    GRAVE:"assets/resources/hex_grave.png",
    BOMB:"assets/resources/tnt.png",
    UNDO:"assets/undo.png",
    BULDOZE:"assets/buldoze.png",
    MOVE:"assets/crane.png",
}
